CONST_UBERTIP_TEXTS = {
    colon = "：",
    def_passive = "未命名空被动",
    def_skill = "未命名技能",
    def_hero = "未命名英雄",
    def_unit = "未命名单位",
    def_item = "未命名物品",
    def_buff = "未命名魔法效果",
    def_upgrade = "未命名科技",
    lv = "等级",
    learn = "学习",
    choose = "选择",
    cd = "冷却",
    sec = "秒",
}